return {
  ["workshop-1089344410"]={ configuration_options={  }, enabled=true },
  ["workshop-1146082006"]={
    configuration_options={ config_fuel_max=90, config_recipe=1, config_spawn_time=30 },
    enabled=true 
  },
  ["workshop-1200745268"]={
    configuration_options={
      Animal=true,
      BuildRepair=true,
      ChopTime=1,
      CookTime=0,
      FishTime=0,
      HSHU=true,
      MineTime=1,
      Others=true,
      Pick=true,
      QuickDry=true,
      QuickGrow=0 
    },
    enabled=true 
  },
  ["workshop-1207269058"]={ configuration_options={  }, enabled=true },
  ["workshop-1290228121"]={
    configuration_options={
      [""]=0,
      Recipe_Tab=0,
      flint=0,
      goldnugget=4,
      language=1,
      moonrocknugget=6,
      nitre=0 
    },
    enabled=true 
  },
  ["workshop-1301033176"]={ configuration_options={ LANG="auto" }, enabled=true },
  ["workshop-352499675"]={
    configuration_options={ [""]=0, Mode="normal", ShelterLight="yes", ShelterUses=5 },
    enabled=true 
  },
  ["workshop-362175979"]={ configuration_options={ ["Draw over FoW"]="disabled" }, enabled=true },
  ["workshop-375850593"]={ configuration_options={  }, enabled=true },
  ["workshop-378160973"]={
    configuration_options={
      ENABLEPINGS=true,
      FIREOPTIONS=2,
      OVERRIDEMODE=false,
      SHAREMINIMAPPROGRESS=true,
      SHOWFIREICONS=true,
      SHOWPLAYERICONS=true,
      SHOWPLAYERSOPTIONS=2 
    },
    enabled=true 
  },
  ["workshop-380423963"]={
    configuration_options={
      [""]=0,
      boulder_blue=0.2,
      boulder_purple=0.05,
      change_cave_loot=false,
      common_loot_charcoal=0,
      common_loot_flint=0.35,
      common_loot_rocks=0.35,
      cutlichen=0,
      durian=0,
      flintless_blue=0.5,
      flintless_purple=0.1,
      flintless_red=0.2,
      foliage=0,
      gears=0,
      goldvein_purple=0.05,
      goldvein_red=0.1,
      guano=0,
      ice=0,
      lightbulb=0,
      moon_green=0.02,
      moon_orange=0.02,
      moon_yellow=0.02,
      pinecone=0,
      rare_loot_bluegem=0.015,
      rare_loot_marble=0.015,
      rare_loot_redgem=0.015,
      rottenegg=0,
      seeds=0,
      spoiled_food=0,
      stalagmite_green=0.02,
      stalagmite_orange=0.02,
      stalagmite_yellow=0.02,
      uncommon_loot_goldnugget=0.05,
      uncommon_loot_mole=0.05,
      uncommon_loot_nitre=0.05,
      uncommon_loot_rabbit=0.05 
    },
    enabled=true 
  },
  ["workshop-444235588"]={
    configuration_options={
      deluxeEndoFirepitBurnRate=0.75,
      deluxeFirepitBurnRate=0.75,
      dropLoot="yes",
      endoDropLoot="yes",
      heatStarBurnRate=0.9,
      heatStarDropLoot="yes",
      iceStarBurnRate=0.9,
      iceStarDropLoot="yes",
      recipeCost="standard",
      starsSpawnHounds="no" 
    },
    enabled=true 
  },
  ["workshop-458587300"]={ configuration_options={ Ownership=false, Travel_Cost=32 }, enabled=true },
  ["workshop-462434129"]={
    configuration_options={
      MOD_RESTART_ALLOW_KILL=true,
      MOD_RESTART_ALLOW_RESTART=true,
      MOD_RESTART_ALLOW_RESURRECT=true,
      MOD_RESTART_CD_BONUS=0,
      MOD_RESTART_CD_KILL=3,
      MOD_RESTART_CD_MAX=0,
      MOD_RESTART_CD_RESTART=5,
      MOD_RESTART_CD_RESURRECT=7,
      MOD_RESTART_FORCE_DROP_MODE=0,
      MOD_RESTART_IGNORING_ADMIN=true,
      MOD_RESTART_MAP_SAVE=2,
      MOD_RESTART_RESURRECT_HEALTH=0,
      MOD_RESTART_TRIGGER_MODE=1,
      MOD_RESTART_WELCOME_TIPS=true,
      MOD_RESTART_WELCOME_TIPS_TIME=6 
    },
    enabled=true 
  },
  ["workshop-577104313"]={
    configuration_options={ ice_created=10, machine_required=2, nitre_required=4, recipe_difficulty=1 },
    enabled=true 
  },
  ["workshop-622448972"]={
    configuration_options={
      health_enhance=false,
      health_regen=true,
      regen_value=50,
      wall_undeployable=false 
    },
    enabled=true 
  },
  ["workshop-666155465"]={
    configuration_options={
      chestB=-1,
      chestG=-1,
      chestR=-1,
      food_estimation=-1,
      food_order=0,
      food_style=0,
      lang="auto",
      show_food_units=-1,
      show_uses=-1 
    },
    enabled=true 
  },
  ["workshop-682721879"]={ configuration_options={  }, enabled=true },
  ["workshop-785295023"]={
    configuration_options={
      bossres=true,
      companion=true,
      dist=2.5,
      healthmul=-1,
      language="AUTO",
      minimapicon=false,
      ownership=0,
      rebounddmg=0,
      recipe="normal",
      recipe_door=true,
      recipe_fence=true,
      recipe_tool=true,
      recipe_vanilla=false,
      recipe_wall=true 
    },
    enabled=true 
  },
  ["workshop-841471368"]={
    configuration_options={
      admin_option=true,
      ancient_altar_no_destroy=false,
      auto_stack=false,
      beefalo_power=false,
      cant_destroyby_monster=false,
      clean_custom="",
      clean_level=-1,
      clean_period=10,
      connect_worlds=false,
      door_lock="000",
      eyeturret_player=false,
      fence_lock="000",
      firesuppressor_dig=30,
      give_start_item=true,
      house_plain_nodestroy=false,
      is_allow_build_near=false,
      krampus_sack_ice=false,
      language="normal",
      minotaur_destroy=false,
      minotaur_regenerate=30,
      pack_pickup=false,
      permission_mode=true,
      portal_clear=40,
      remove_owner_time="never",
      spread_fire=1,
      test_mode=false,
      trap_teeth_player=false,
      wall_hay_lock="000",
      wall_moonrock_lock="000",
      wall_ruins_lock="000",
      wall_stone_lock="000",
      wall_wood_lock="000" 
    },
    enabled=true 
  },
  ["workshop-934638020"]={ configuration_options={  }, enabled=true } 
}